adding smoke test function

diff --git a/.github/workflows/deployapi.yml b/.github/workflows/deployapi.yml
--- a/.github/workflows/deployapi.yml
+++ b/.github/workflows/deployapi.yml
@@ -36,12 +36,50 @@ jobs:
 
 
       # deploy to azure webapp
-      - name: 'Run Azure webapp deploy action using publish profile credentials'
-        uses: azure/webapps-deploy@v1
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    
+    steps:
+        - name: 'Run Azure webapp deploy action using publish profile credentials'
+          uses: azure/webapps-deploy@v1
+          with:
+            app-name: ${{ env.AZURE_WEBAPP_NAME }}
+            publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
+            package: ./publish
+
+
+  # Add steps to build and deploy your Azure Functions application
+  smoke-test:
+    needs: deploy
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: 'Checkout Repository'
+        uses: actions/checkout@v2
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v2
         with:
-          app-name: ${{ env.AZURE_WEBAPP_NAME }}
-          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
-          package: ./publish
+          node-version: '14'
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: Run Smoke Test
+        run: |
+          function_url="https://ea-assignment3-smoketest.azurewebsites.net"
+
+          status_code=$(curl -s -o /dev/null -w "%{http_code}" $function_url)
+
+          echo "Status Code: $status_code"
+
+          if [ "$status_code" -ne 200 ]; then
+            echo "Smoke Test failed!"
+            exit 1
+          fi
+
+          echo "Smoke Test passed!"
 
 
   
